<a href="https://colab.research.google.com/github/dhrumilrdg142/Fetureengineering/blob/main/fetureengineering(practice_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
db = pd.read_csv('/content/Foodpanda Analysis Dataset.csv')

In [3]:
db

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,C5663,Male,Adult,Peshawar,1/14/2024,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,3,10/14/2024,Cancelled
1,C2831,Male,Adult,Multan,7/7/2024,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2,8/21/2025,Delayed
2,C2851,Other,Senior,Multan,6/20/2025,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3,9/19/2024,Delayed
3,C1694,Female,Senior,Peshawar,9/5/2023,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2,6/29/2025,Delayed
4,C4339,Other,Senior,Lahore,12/29/2023,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,3,3/6/2025,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,C6849,Male,Adult,Multan,11/25/2024,O10849,8/22/2025,Pizza Hut,Burger,Italian,4,875.71,Cash,28,11/29/2024,166,Active,5,12/30/2024,Cancelled
5996,C3787,Female,Adult,Islamabad,1/28/2025,O7787,8/22/2025,KFC,Pizza,Italian,5,1118.26,Cash,12,6/8/2025,193,Inactive,3,2/9/2025,Delayed
5997,C2841,Other,Teenager,Islamabad,10/19/2023,O6841,8/22/2025,KFC,Sandwich,Italian,4,1005.83,Card,31,12/30/2024,278,Active,4,3/23/2025,Cancelled
5998,C1624,Male,Adult,Islamabad,6/17/2024,O5624,8/22/2025,KFC,Fries,Fast Food,4,1226.10,Card,37,12/27/2024,55,Inactive,2,3/15/2025,Delivered
5999,C2068,Female,Adult,Multan,3/15/2025,O6068,8/22/2025,Burger King,Fries,Fast Food,3,1131.27,Card,2,6/13/2025,41,Inactive,1,7/15/2025,Delayed

In [4]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      6000 non-null   object
 1   gender           6000 non-null   object
 2   age              6000 non-null   object
 3   city             6000 non-null   object
 4   signup_date      6000 non-null   object
 5   order_id         6000 non-null   object
 6   order_date       6000 non-null   object
 7   restaurant_name  6000 non-null   object
 8   dish_name        6000 non-null   object
 9   category         6000 non-null   object
 10  quantity         6000 non-null   int64
 11  price            6000 non-null   float64
 12  payment_method   6000 non-null   object
 13  order_frequency  6000 non-null   int64
 14  last_order_date  6000 non-null   object
 15  loyalty_points   6000 non-null   int64
 16  churned          6000 non-null   object
 17  rating           6000 non-null   int64
 18  rating_date      6000 non-null   object
 19  delivery_status  6000 non-null   object
dtypes: float64(1), int64(4), object(15)
memory usage: 937.6+ KB

In [7]:
db.describe()

          quantity        price  order_frequency  loyalty_points       rating
count  6000.000000  6000.000000      6000.000000     6000.000000  6000.000000
mean      2.991667   800.524880        25.304667      250.173667     2.996833
std       1.414778   404.855029        14.358930      144.608478     1.406113
min       1.000000   100.300000         1.000000        0.000000     1.000000
25%       2.000000   441.997500        13.000000      125.000000     2.000000
50%       3.000000   806.460000        25.000000      249.500000     3.000000
75%       4.000000  1149.737500        37.000000      378.000000     4.000000
max       5.000000  1499.950000        50.000000      500.000000     5.000000

In [9]:
db['customer_id'].value_counts()

customer_id
C4870    1
C1955    1
C1450    1
C4726    1
C4417    1
        ..
C4339    1
C1694    1
C2851    1
C2831    1
C5663    1
Name: count, Length: 6000, dtype: int64

In [12]:
# Remove the letter 'C' (case-insensitive)
db['customer_id'] = db['customer_id'].astype(str).str.replace('C', '', case=False)

# (Optional) Convert to integer type if you want numbers only
db['customer_id'] = db['customer_id'].astype(int)

In [13]:
db

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,5663,Male,Adult,Peshawar,1/14/2024,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,3,10/14/2024,Cancelled
1,2831,Male,Adult,Multan,7/7/2024,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2,8/21/2025,Delayed
2,2851,Other,Senior,Multan,6/20/2025,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3,9/19/2024,Delayed
3,1694,Female,Senior,Peshawar,9/5/2023,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2,6/29/2025,Delayed
4,4339,Other,Senior,Lahore,12/29/2023,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,3,3/6/2025,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,6849,Male,Adult,Multan,11/25/2024,O10849,8/22/2025,Pizza Hut,Burger,Italian,4,875.71,Cash,28,11/29/2024,166,Active,5,12/30/2024,Cancelled
5996,3787,Female,Adult,Islamabad,1/28/2025,O7787,8/22/2025,KFC,Pizza,Italian,5,1118.26,Cash,12,6/8/2025,193,Inactive,3,2/9/2025,Delayed
5997,2841,Other,Teenager,Islamabad,10/19/2023,O6841,8/22/2025,KFC,Sandwich,Italian,4,1005.83,Card,31,12/30/2024,278,Active,4,3/23/2025,Cancelled
5998,1624,Male,Adult,Islamabad,6/17/2024,O5624,8/22/2025,KFC,Fries,Fast Food,4,1226.10,Card,37,12/27/2024,55,Inactive,2,3/15/2025,Delivered
5999,2068,Female,Adult,Multan,3/15/2025,O6068,8/22/2025,Burger King,Fries,Fast Food,3,1131.27,Card,2,6/13/2025,41,Inactive,1,7/15/2025,Delayed

In [17]:
db["signup_date"].value_counts()

signup_date
10/18/2023    18
5/25/2025     16
12/30/2024    16
8/15/2024     16
7/18/2025     16
              ..
12/18/2023     2
4/1/2025       2
5/21/2025      2
12/14/2023     2
9/22/2023      2
Name: count, Length: 730, dtype: int64

In [19]:
db['signup_date'] = pd.to_datetime(db['signup_date'], format='%m/%d/%Y')

In [20]:
db

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,5663,Male,Adult,Peshawar,2024-01-14,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,3,10/14/2024,Cancelled
1,2831,Male,Adult,Multan,2024-07-07,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2,8/21/2025,Delayed
2,2851,Other,Senior,Multan,2025-06-20,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3,9/19/2024,Delayed
3,1694,Female,Senior,Peshawar,2023-09-05,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2,6/29/2025,Delayed
4,4339,Other,Senior,Lahore,2023-12-29,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,3,3/6/2025,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,6849,Male,Adult,Multan,2024-11-25,O10849,8/22/2025,Pizza Hut,Burger,Italian,4,875.71,Cash,28,11/29/2024,166,Active,5,12/30/2024,Cancelled
5996,3787,Female,Adult,Islamabad,2025-01-28,O7787,8/22/2025,KFC,Pizza,Italian,5,1118.26,Cash,12,6/8/2025,193,Inactive,3,2/9/2025,Delayed
5997,2841,Other,Teenager,Islamabad,2023-10-19,O6841,8/22/2025,KFC,Sandwich,Italian,4,1005.83,Card,31,12/30/2024,278,Active,4,3/23/2025,Cancelled
5998,1624,Male,Adult,Islamabad,2024-06-17,O5624,8/22/2025,KFC,Fries,Fast Food,4,1226.10,Card,37,12/27/2024,55,Inactive,2,3/15/2025,Delivered
5999,2068,Female,Adult,Multan,2025-03-15,O6068,8/22/2025,Burger King,Fries,Fast Food,3,1131.27,Card,2,6/13/2025,41,Inactive,1,7/15/2025,Delayed

In [22]:
db['signup_date'] = db['signup_date'].astype(str).str.replace('-', '')

In [23]:
db

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,5663,Male,Adult,Peshawar,20240114,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,3,10/14/2024,Cancelled
1,2831,Male,Adult,Multan,20240707,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2,8/21/2025,Delayed
2,2851,Other,Senior,Multan,20250620,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3,9/19/2024,Delayed
3,1694,Female,Senior,Peshawar,20230905,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2,6/29/2025,Delayed
4,4339,Other,Senior,Lahore,20231229,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,3,3/6/2025,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,6849,Male,Adult,Multan,20241125,O10849,8/22/2025,Pizza Hut,Burger,Italian,4,875.71,Cash,28,11/29/2024,166,Active,5,12/30/2024,Cancelled
5996,3787,Female,Adult,Islamabad,20250128,O7787,8/22/2025,KFC,Pizza,Italian,5,1118.26,Cash,12,6/8/2025,193,Inactive,3,2/9/2025,Delayed
5997,2841,Other,Teenager,Islamabad,20231019,O6841,8/22/2025,KFC,Sandwich,Italian,4,1005.83,Card,31,12/30/2024,278,Active,4,3/23/2025,Cancelled
5998,1624,Male,Adult,Islamabad,20240617,O5624,8/22/2025,KFC,Fries,Fast Food,4,1226.10,Card,37,12/27/2024,55,Inactive,2,3/15/2025,Delivered
5999,2068,Female,Adult,Multan,20250315,O6068,8/22/2025,Burger King,Fries,Fast Food,3,1131.27,Card,2,6/13/2025,41,Inactive,1,7/15/2025,Delayed

In [24]:
db['order_id']

0        O9663
1        O6831
2        O6851
3        O5694
4        O8339
         ...
5995    O10849
5996     O7787
5997     O6841
5998     O5624
5999     O6068
Name: order_id, Length: 6000, dtype: object

In [37]:
db['rating_date'] = db['rating_date'].astype(str).str.replace('/', '')

In [38]:
db

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,5663,Male,Adult,Peshawar,20240114,O9663,8232023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7192025,238,Active,3,10142024,Cancelled
1,2831,Male,Adult,Multan,20240707,O6831,8232023,KFC,Burger,Italian,3,956.04,Wallet,24,11252024,81,Active,2,8212025,Delayed
2,2851,Other,Senior,Multan,20250620,O6851,8232023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5102025,82,Inactive,3,9192024,Delayed
3,1694,Female,Senior,Peshawar,20230905,O5694,8232023,Subway,Pizza,Dessert,4,231.30,Card,27,7242025,45,Inactive,2,6292025,Delayed
4,4339,Other,Senior,Lahore,20231229,O8339,8242023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12212024,418,Inactive,3,362025,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,6849,Male,Adult,Multan,20241125,O10849,8222025,Pizza Hut,Burger,Italian,4,875.71,Cash,28,11292024,166,Active,5,12302024,Cancelled
5996,3787,Female,Adult,Islamabad,20250128,O7787,8222025,KFC,Pizza,Italian,5,1118.26,Cash,12,682025,193,Inactive,3,292025,Delayed
5997,2841,Other,Teenager,Islamabad,20231019,O6841,8222025,KFC,Sandwich,Italian,4,1005.83,Card,31,12302024,278,Active,4,3232025,Cancelled
5998,1624,Male,Adult,Islamabad,20240617,O5624,8222025,KFC,Fries,Fast Food,4,1226.10,Card,37,12272024,55,Inactive,2,3152025,Delivered
5999,2068,Female,Adult,Multan,20250315,O6068,8222025,Burger King,Fries,Fast Food,3,1131.27,Card,2,6132025,41,Inactive,1,7152025,Delayed

In [50]:
db["delivery_status"].value_counts()

delivery_status
0    1
1    1
2    1
Name: count, dtype: int64

In [49]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_status      3 non-null      int64
 1   delivery_status_num  3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes